DateValidityCheck

diff --git a/corona b/corona
--- a/corona
+++ b/corona
@@ -59,39 +59,20 @@ help(){
 }
 
 
-#validateAfterTime(){
-#	if expr "$afterTime" : "^[0-9][0-9][0-9][0-9]\-[0-9][0-9]\-[0-9][0-9]"; then
-#		$(echo $1 | awk -F \- '$2 > 12  || $2 <= 0 {exit 1}')
-#		if [ $? -eq 0 ]; then
-#			shift
-#			atCount=$((atCount+1))
-#			echo "Date Correct"
-#			break
-#		else
-#			errorDate
-#		fi
-#	else
-#		errorDateSpec
-#	fi
-#}
-
-
-
-
 
 
 ########	ERROR SECTION	########
 
 errorDate(){
-	echo "Invalid date!" >&2
+	echo "Invalid date on filter \"$1\"!" >&2
 	exit 1
 }
 errorDateSpec(){
-	echo "Wrong date format (YYYY-MM-DD) / date not specified!" >&2
+	echo "Wrong date format (YYYY-MM-DD) on filter \"$1\" / date not specified!" >&2
 	exit 1
 }
 errorMultipleFilter(){
-	echo "Multiple usage of same filter!"
+	echo "Multiple usage of same filter \"$1\"!" >&2
 	exit 1
 }
 
@@ -102,32 +83,115 @@ errorMultipleFilter(){
 afterTime="0"
 atCount=0
 
+beforeTime="0"
+btCount=0
+
+
+
+########	Validation	########
+validateDate(){
+	if [ "$1" = "-a" ]; then
+		if [ $atCount -eq 1 ]; then
+				errorMultipleFilter "$1"
+		fi
+	else 
+		if [ $btCount -eq 1 ]; then
+				errorMultipleFilter "$1"
+		fi
+	fi
+	if expr "$2" : "^[0-9][0-9][0-9][0-9]\-[0-9][0-9]\-[0-9][0-9]">/dev/null; then
+			# Year Validation
+			$(echo $2 | awk -F \- '$1 == 0 {exit 1}') # This depends if gregorian calendar 1582 is counted
+			if [ $? -eq 0 ]; then
+				# Month Validation
+				$(echo $2 | awk -F \- '$2 > 12 || $2 <= 0{exit 1}')
+				if [ $? -eq 0 ]; then
+					# Day Validation
+					$(echo $2 | awk -F \- '{
+						if($2 == 1 && ($3 > 31 || $3 <= 0)){
+							exit 1
+						}
+						else if ($2 == 2 && ($1 % 4) != 0 && ($3 > 28 || $3 <= 0)){
+							exit 1
+						} 
+						else if ($2 == 2 && ($1 % 4) == 0 && ($3 > 29 || $3 <= 0)){
+							exit 1
+						}
+						else if($2 == 3 && ($3 > 31 || $3 <= 0)){
+							exit 1
+						}
+						else if($2 == 4 && ($3 > 30 || $3 <= 0)){
+							exit 1
+						}
+						else if($2 == 5 && ($3 > 31 || $3 <= 0)){
+							exit 1
+						}
+						else if($2 == 6 && ($3 > 30 || $3 <= 0)){
+							exit 1
+						}
+						else if($2 == 7 && ($3 > 31 || $3 <= 0)){
+							exit 1
+						}
+						else if($2 == 8 && ($3 > 31 || $3 <= 0)){
+							exit 1
+						}
+						else if($2 == 9 && ($3 > 30 || $3 <= 0)){
+							exit 1
+						}
+						else if($2 == 10 && ($3 > 31 || $3 <= 0)){
+							exit 1
+						}
+						else if($2 == 11 && ($3 > 30 || $3 <= 0)){
+							exit 1
+						}
+						else if($2 == 12 && ($3 > 31 || $3 <= 0)){
+							exit 1
+						}
+						
+						}')
+					if [ $? -eq 0 ]; then
+						if [ "$1" = "-a" ]; then
+							atCount=$((atCount+1))
+							echo "Date Correct"
+							return 0
+						else
+							btCount=$((btCount+1))	
+							echo "Date Correct"
+							return 0
+						fi				
+					else	
+						errorDate "$1"
+					fi
+				else
+					errorDate "$1"
+				fi
+			else
+				errorDate "$1"
+			fi
+		else
+			errorDateSpec "$1"
+		fi
+}
+
+
+
 ########	Control Code	########
 while [ $# -gt 0 ]; do
 	option="$1"
 
       case "$option" in
         "-h")	help; shift;;
-	"-a")	if [ $atCount -eq 1 ]; then
-			errorMultipleFilter
-		fi
+	"-a")	
 		afterTime="$2"
-		if expr "$afterTime" : "^[0-9][0-9][0-9][0-9]\-[0-9][0-9]\-[0-9][0-9]"; then
-			$(echo $afterTime | awk -F \- '$2 > 12 || $2 <= 0{exit 1}')
-			if [ $? -eq 0 ]; then
-				shift
-				shift
-				atCount=$((atCount+1))
-				echo "Date Correct"
-			else
-				errorDate
-			fi
-		else
-			errorDateSpec
-		fi;;
-	"-b")	afterTime="$2"
-		validateAfterTime "$afterTime";;
-
+		validateDate "$1" "$2"
+		shift
+		shift;;
+		
+	"-b")	
+		beforeTime="$2"
+		validateDate "$1" "$2"
+		shift
+		shift;;
        	*)	echo "ERROR: Invalid option: \""$option"\"" >&2
 		exit 1;;
       esac
